### ISSUE TITLE
Описание правил кодирования для Backend

### ISSUE THREAD

**Issue by shlyapos** [shlyapos/TrackTor#4]
Нужно написать какие-нибудь правила для написания backend кода, кпримеру: отступы, использование каких-либо ключевых слов и т.д.

**Comment by garasev** [comment]
@PESPSA я написал [тут](https://github.com/shlyapos/TrackTor/wiki/Регламенты-кодирования#backend), ты [там](https://github.com/shlyapos/TrackTor/wiki/Регламенты-кодирования#backend) посмотри, и если чет не нравится [сюда](https://github.com/shlyapos/TrackTor/issues/4) напиши, обсудим, исправим

**Comment by PESPSA** [comment]
@garasev можно было бы добавить подраздел с форматом DTO, либо описывать это уже на другой специальной странице

**Comment by garasev** [comment]
> @garasev можно было бы добавить подраздел с форматом DTO, либо описывать это уже на другой специальной странице

Ну dto тут совершенно не при чем, здесь мы обговариваем правила написания не кода. Посмотри и скажи, что касаемо правилами написания кода можно ещё уточнить.

**Comment by PESPSA** [comment]
@garasev я доволен, issue можно закрывать
