### ISSUE TITLE
Подготовить ER модель базы данных

### ISSUE THREAD

**Issue by garasev** [shlyapos/TrackTor#6]
Описать такие сущности, как:
1)  Пользователь
Поля: 
* id
* логин
* хеш
* соль
2) Трек
Поля: 
* id
* id автора
* название
* тип транспорта
* регион/город
3) Чекпоинт трека
Поля: 
* id
* id трека
* широта
* долгота
4) Результат
Поля: 
* id 
* id пользователя
* id трека
* рекордное время

Залить исходник и .png файл в папку /docs/images проекта

**Comment by PESPSA** [comment]
@garasev PR [тут](https://github.com/shlyapos/TrackTor/pull/12), поставил его на проверку Саней еще
